##ansible task for installing logstash 
---
- name: add logsatsh key
  apt_key: url={{ url_keylogstash }} state=present

- name: create logsatsh repo list
  copy: content={{ repo_logstash }} dest=/etc/apt/sources.list.d/logstash.list

- name: install Logstash
  apt: name=logstash state=latest update_cache=yes

- name: Add config logstash
  template: src=main.j2 dest=/etc/logstash/conf.d/main.conf
  notify: 
      - Restart logstash
