#!/bin/bash

start(){
    FILE=/tmp/elasticsearch.pid
    if [ -f $FILE ];
    then
      echo "Elasticsearch is already running..."
    else
      echo "Running elasticsearch..."
      /bin/sh /etc/elasticsearch/bin/elasticsearch >> /var/log/elasticsearch/elasticsearch.log &
      echo "$!" > /tmp/elasticsearch.pid
      echo "[OK]"
    fi
}

stop(){
    FILE=/tmp/elasticsearch.pid
    if [ -f $FILE ]
    then
      echo "Stopping elasticsearch..."
      kill $(cat /tmp/elasticsearch.pid) && rm -rf /tmp/elasticsearch.pid
      echo "[Stopped]"
    else
      echo "Elasticsearch is not running..."
    fi
}

status(){
    FILE=/tmp/elasticsearch.pid
    if [ -f $FILE ];
    then
      echo "Elasticsearch is running..."
    else
      echo "Elasticsearch is stopped..."
    fi
}

case "$1" in
start)
    start
;;
stop)
    stop
;;
restart)
    stop
    start
;;
status)
    status
;;
*)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
;;
esac

exit 0
