#!/bin/bash

start(){
    FILE=/tmp/kibana.pid
    if [ -f $FILE ];
    then
      echo "Kibana is already running..."
    else
      echo "Running kibana..."
      /bin/sh /etc/kibana/bin/kibana >> /var/log/kibana.log &
      echo "$!" > /tmp/kibana.pid
      echo "[OK]"
    fi
}

stop(){
    FILE=/tmp/kibana.pid
    if [ -f $FILE ]
    then
      echo "Stopping kibana..."
      kill $(cat /tmp/kibana.pid) && rm -rf /tmp/kibana.pid
      echo "[Stopped]"
    else
      echo "Kibana is not running..."
    fi
}

status(){
    FILE=/tmp/kibana.pid
    if [ -f $FILE ];
    then
      echo "Kibana is running..."
    else
      echo "Kibana is stopped..."
    fi
}

case "$1" in
start)
    start
;;
stop)
    stop
;;
restart)
    stop
    start
;;
status)
    status
;;
*)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
;;
esac

exit 0
